### PR TITLE
[DEVOPS-2019] Prepare application for deployment

### PR DESCRIPTION
**Pull request by itskingori**
Title says it all.

### Related PRs

* https://github.com/Intellection/docker-base-images/pull/183
* https://github.com/Intellection/kubernetes-config-pack/pull/1975
* https://github.com/Intellection/jenkins-job-builder-configs/pull/223

### CODE REVIEW

**Review by itskingori — COMMENTED** [review]
**Sandbox:** https://developers.sandbox.zappi.io
**Production:** https://developers.zappi.io

This is how it looks:

Screenshot 2021-10-01 at 13 09 01

**Comment by benmmari** [comment]
❤️  love this. Thanks @itskingori !

**Review by benmmari — APPROVED** [review]
I may be a taaaad bit bias but this definitely looks good to me 👍 🚀

**Review by hadrianvalentine — APPROVED** [review]

**Pull request merged**
